
name: DeployNextjs

on:
  push:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: leocodes.com
        username: root
        key: ${{ secrets.LEO_SECRET }}
        port: 22
        script: |
          cd /var/www/leo
          git pull leo master
          npx next build
          pm2 restart 1